# Generated by Django 5.2.15 on 2026-09-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(help_text='Start date of holiday/event')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for multi-day events', null=True)),
                ('category', models.CharField(choices=[('holiday', 'Public / Academic Holiday'), ('exam', 'Examination Period'), ('event', 'University Event / Festival'), ('deadline', 'Academic Deadline'), ('vacation', 'Semester Break / Vacation')], default='holiday', max_length=20)),
                ('department', models.CharField(blank=True, help_text='Leave blank for all departments', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Holiday / Academic Event',
                'verbose_name_plural': 'Holidays & Academic Events',
                'ordering': ['date'],
            },
        ),
    ]
