# Generated by Django 5.2.15 on 2026-09-14 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_academicterm_assignmentsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('midterm', 'Mid-Term Exam'), ('endterm', 'End-Term Exam'), ('practical', 'Practical Exam'), ('quiz', 'Quiz / Unit Test')], default='endterm', max_length=20)),
                ('exam_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('venue', models.CharField(help_text='e.g., Exam Hall A, Room 302', max_length=100)),
                ('seat_number', models.CharField(blank=True, max_length=50)),
                ('semester', models.CharField(blank=True, max_length=10)),
                ('hall_ticket_released', models.BooleanField(default=False, help_text='Whether hall tickets are released and downloadable for this exam')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('academic_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_schedules', to='courses.academicterm')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schedules', to='courses.subject')),
            ],
            options={
                'ordering': ['exam_date', 'start_time'],
            },
        ),
    ]
